---
title: "The endometrial transcriptome transition preceding receptivity to embryo implantation in mice"
site: workflowr::wflow_site
---
### Hon Yeung Chan^1^, Ha M. Tran^1^, Jimmy Breen^1^, John E. Schjenken^1,2,3^ and Sarah A. Robertson^1\*^

**Keywords: RNA sequencing, uterus, embryo implantation, endometrial receptivity, mouse**

**Author affiliations:**

^1^ The Robinson Research Institute and Adelaide Medical School, University of Adelaide, Adelaide, SA 5000, Australia.
^2^ Hunter Medical Research Institute, Infertility and Reproduction Research Program, New Lambton Heights, NSW 2305, Australia.
^3^ Priority Research Centre for Reproductive Science, School of Environmental and Life Sciences, Discipline of Biological Sciences, The University of Newcastle, University Drive, Callaghan, NSW 2308, Australia

^\*^ **Corresponding author:** Sarah A. Robertson, The Robinson Research Institute, Adelaide Medical School, University of Adelaide, Adelaide, SA 5005, Australia. 

E-mail: sarah.robertson@adelaide.edu.au

**Conflict of Interest Statement:** The authors have declared that no conflict of interest exists

# Abstract

Receptivity of the uterus is essential for embryo implantation and progression of pregnancy. Acquisition of receptivity involves major molecular and cellular changes in the endometrial lining of the uterus from its non-receptive state at ovulation, to its receptive state four days later. The precise molecular mechanisms underlying this transition remain to be fully characterized. Here, we aimed to generate a comprehensive profile of the uterine transcriptome in the peri-ovulatory and peri-implantation states, and to define the differences between them, in the mouse. High throughput RNA-sequencing was utilized to identify genes and pathways expressed in the endometrium of unmated estrous female C57Bl/6 mice, and in female mice on day 3.5 post-coitum (pc) after mating with BALB/c males (n=3-4 biological replicates). Compared to the endometrium at estrus, 388 genes were differentially expressed in the endometrium on day 3.5 post-coitum (FDR ≤ 0.05). The transcriptional changes indicated substantial modulation of uterine immune and vascular systems during the pre-implantation phase, with the functional terms Angiogenesis, Chemotaxis, and Lymphangiogenesis predominating. Ingenuity Pathway Analysis software revealed several upstream regulators implicated in the transition to receptivity including various cytokines, steroid hormones, prostaglandin E2, and vascular endothelial growth factor A. This study confirms that the transcriptome of a receptive uterus is vastly different to the non-receptive uterus and identifies several genes, regulatory pathways, and upstream drivers in addition to those previously associated with implantation. This dataset will serve as a valuable tool and resource for future research on the molecular mechanisms of uterine receptivity.